apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cems-ingress
  namespace: cems-nginx
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: cems.danskebank.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: retail-service
            port:
              number: 80
